"""graph_fy install/uninstall subsystem.

The per-platform skill/hook installers and uninstallers, extracted verbatim from
graph_fy/__main__.py so the CLI dispatcher (`main`) stays readable. Import path is
unchanged: `graph_fy.__main__` re-exports every name defined here, so
`from graph_fy.__main__ import claude_install` (etc.) keeps working.

Lives at graph_fy/install.py (same package dir as __main__) on purpose: the
installers resolve packaged assets via `Path(__file__).parent / "always_on"` and
`/ "skills"`, which only works from within the graph_fy/ directory.
"""

from __future__ import annotations
import functools
import json
import os
import platform
import re
import shutil
import stat
import sys
from pathlib import Path
from typing import NoReturn

try:
    from importlib.metadata import version as _pkg_version

    try:
        __version__ = _pkg_version("graph_fy")
    except Exception:
        __version__ = _pkg_version("graph_fyy")
except Exception:
    __version__ = "unknown"

from graph_fy.paths import graph_fy_OUT as _graph_fy_OUT
from graph_fy.paths import os_replace_with_fallback as _os_replace_with_fallback


def _safe_mkdir(path: Path) -> None:
    """Create directory and parents safely, handling dangling symlinks in the hierarchy."""
    try:
        path.mkdir(parents=True, exist_ok=True)
    except FileExistsError:
        path.resolve().mkdir(parents=True, exist_ok=True)


def _write_version_stamp(skill_dst: Path, version: str) -> None:
    """Atomically write ``.graph_fy_version`` beside ``skill_dst``.

    Matches the SKILL.md install path: temp file in the same directory, then
    ``os.replace``. Unlike ``Path.write_text`` (and unlike
    ``paths.write_text_atomic``, which resolves through symlinks), ``os.replace``
    replaces a managed symlink in place — consistent with SKILL.md /
    ``references/`` and crash-safe against a half-written stamp (#3286).
    """
    version_file = skill_dst.parent / ".graph_fy_version"
    tmp = version_file.with_name(".graph_fy_version.tmp")
    try:
        tmp.write_text(version, encoding="utf-8")
        _os_replace_with_fallback(tmp, version_file)
    except Exception:
        try:
            tmp.unlink(missing_ok=True)
        except OSError:
            pass
        raise


@functools.lru_cache(maxsize=None)
def _always_on(basename: str) -> str:
    """Read a packaged always-on instruction block from graph_fy/always_on/.

    The six always-on blocks (CLAUDE.md / AGENTS.md / GEMINI.md / VS Code
    Copilot instructions / Antigravity rules / Kiro steering) live as committed
    markdown next to this module, generated by tools/skillgen from a single
    human-edited fragment and guarded against drift by ``skillgen --check``. The
    installer injects them verbatim via ``_replace_or_append_section``, so the
    bytes here must match the former triple-quoted constant exactly — the
    always-on-roundtrip validator proves that.
    """
    path = Path(__file__).parent / "always_on" / f"{basename}.md"
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        # Defer to use-time so a missing/corrupt packaged block can't crash module
        # import (which would brick every CLI command, not just install). Reached
        # only by an install/integration path that actually needs this block.
        raise RuntimeError(
            f"graph_fy install is incomplete: missing always-on block '{basename}' "
            f"at {path}. Reinstall graph_fyy (e.g. `uv tool install --reinstall graph_fyy`)."
        ) from exc
def _platform_skill_destination(platform_name: str, *, project: bool = False, project_dir: Path | None = None) -> Path:
    """Return the skill destination for a platform and scope."""
    if platform_name not in _PLATFORM_CONFIG:
        raise KeyError(platform_name)
    cfg = _PLATFORM_CONFIG[platform_name]
    if project:
        return (project_dir or Path(".")) / cfg["skill_dst"]

    if platform_name in ("claude", "windows") and os.environ.get("CLAUDE_CONFIG_DIR"):
        return Path(os.environ["CLAUDE_CONFIG_DIR"]) / "skills" / "graph_fy" / "SKILL.md"
    return Path.home() / cfg["skill_dst"]


def _packaged_skill_refs_dir(platform_name: str) -> Path | None:
    """Return the packaged references source dir for a progressive platform, else None."""
    bundle = _PLATFORM_CONFIG.get(platform_name, {}).get("skill_refs")
    if not bundle:
        return None
    bundle_dir = Path(__file__).parent / "skills" / bundle
    if not bundle_dir.is_dir():
        return None
    return bundle_dir / "references"


def _install_skill_references(skill_dst: Path, refs_src: Path) -> None:
    """Atomically install a packaged references/ sidecar next to SKILL.md.

    Stages the packaged dir into ``references.tmp`` (copytree), drops any stale
    ``references/`` already on disk, then replaces the staged dir into place.
    """
    refs_dst = skill_dst.parent / "references"
    refs_staged = skill_dst.parent / "references.tmp"
    if refs_staged.exists():
        shutil.rmtree(refs_staged)
    try:
        shutil.copytree(refs_src, refs_staged)
        for path in (refs_staged, *refs_staged.rglob("*")):
            path.chmod(path.stat().st_mode | stat.S_IWUSR)
        if refs_dst.exists():
            shutil.rmtree(refs_dst)
        try:
            os.replace(refs_staged, refs_dst)
        except OSError as exc:
            if not isinstance(exc, PermissionError) and getattr(exc, "winerror", None) != 17:
                raise
            if refs_dst.exists():
                shutil.rmtree(refs_dst, ignore_errors=True)
            shutil.copytree(refs_staged, refs_dst)
            shutil.rmtree(refs_staged, ignore_errors=True)
    except Exception:
        if refs_staged.exists():
            shutil.rmtree(refs_staged, ignore_errors=True)
        raise


def _copy_skill_file(platform_name: str, *, project: bool = False, project_dir: Path | None = None) -> Path:
    """Copy a packaged skill file and write its version stamp."""
    skill_file = _PLATFORM_CONFIG[platform_name]["skill_file"]
    skill_src = Path(__file__).parent / skill_file
    if not skill_src.exists():
        print(f"error: {skill_file} not found in package - reinstall graph_fy", file=sys.stderr)
        sys.exit(1)

    refs_src = _packaged_skill_refs_dir(platform_name)
    if refs_src is not None and not refs_src.exists():
        # Progressive platform declared a references bundle that is missing from
        # the package. Fail loud rather than silently shipping an empty sidecar.
        print(
            f"error: references for '{platform_name}' not found in package "
            f"({refs_src}) - reinstall graph_fy",
            file=sys.stderr,
        )
        sys.exit(1)

    skill_dst = _platform_skill_destination(platform_name, project=project, project_dir=project_dir)
    _safe_mkdir(skill_dst.parent)

    # Install the references/ sidecar (or clear an orphan one) BEFORE writing
    # SKILL.md, so SKILL.md is the last artifact laid down. An install that is
    # interrupted partway then leaves no SKILL.md rather than a SKILL.md that
    # points at an absent references/ dir.
    if refs_src is not None:
        _install_skill_references(skill_dst, refs_src)
        print(f"  references       ->  {skill_dst.parent / 'references'}")
    else:
        # Monolith (or progressive-with-no-refs): clear any orphan references/.
        orphan_refs = skill_dst.parent / "references"
        if orphan_refs.exists():
            shutil.rmtree(orphan_refs)

    # A SKILL.md that differs from what is about to be written may carry the
    # user's local edits (a tuned description:, extra guidance); replacing it
    # wholesale with only "skill installed ->" for output read like a no-op
    # while the edits were gone (#3144). Keep one .bak beside it and say so.
    # Every upgrade differs too - the .bak is overwritten each install, so it
    # always holds exactly the previous copy.
    try:
        if skill_dst.exists() and skill_dst.read_bytes() != skill_src.read_bytes():
            backup = skill_dst.with_suffix(skill_dst.suffix + ".bak")
            shutil.copy2(skill_dst, backup)
            print(f"  previous copy    ->  {backup} (differed from the packaged skill)")
    except OSError:
        pass  # a failed backup must not block the install
    # SKILL.md last (crash-safety), via an atomic temp + rename.
    tmp_dst = skill_dst.with_suffix(skill_dst.suffix + ".tmp")
    try:
        shutil.copy(skill_src, tmp_dst)
        _os_replace_with_fallback(tmp_dst, skill_dst)
    except Exception:
        try:
            tmp_dst.unlink(missing_ok=True)
        except OSError:
            pass
        raise

    _write_version_stamp(skill_dst, __version__)
    print(f"  skill installed  ->  {skill_dst}")
    return skill_dst
def _remove_skill_file(platform_name: str, *, project: bool = False, project_dir: Path | None = None) -> bool:
    """Remove a platform skill file and its version stamp without touching other scopes."""
    skill_dst = _platform_skill_destination(platform_name, project=project, project_dir=project_dir)
    removed = False
    if skill_dst.exists():
        skill_dst.unlink()
        print(f"  skill removed    ->  {skill_dst}")
        removed = True
    version_file = skill_dst.parent / ".graph_fy_version"
    if version_file.exists():
        version_file.unlink()
        removed = True
    refs_dir = skill_dst.parent / "references"
    if refs_dir.exists():
        shutil.rmtree(refs_dir)
        removed = True
    for d in (skill_dst.parent, skill_dst.parent.parent, skill_dst.parent.parent.parent):
        try:
            d.rmdir()
        except OSError:
            break
    return removed
def _project_scope_root(path: Path, project_dir: Path) -> Path:
    """Return the top-level project artifact for a project-scoped skill path."""
    try:
        rel = path.relative_to(project_dir)
    except ValueError:
        return path
    return project_dir / rel.parts[0] if rel.parts else path
def _remove_claude_skill_registration(project_dir: Path) -> None:
    """Remove the project-scoped Claude skill registration file/section."""
    claude_md = project_dir / ".claude" / "CLAUDE.md"
    if not claude_md.exists():
        return
    content = claude_md.read_text(encoding="utf-8")
    # Match the exact H1 `# graph_fy` registration heading, never a substring of a
    # user's `## graph_fy`/`### graph_fy` (#2062). Section runs to the next H1.
    cleaned = _remove_marker_section(content, "# graph_fy", boundary_prefix="# ")
    if cleaned is None:
        return
    if cleaned:
        claude_md.write_text(cleaned + "\n", encoding="utf-8")
        print(f"  CLAUDE.md        ->  graph_fy skill registration removed from {claude_md}")
    else:
        claude_md.unlink()
        print(f"  CLAUDE.md        ->  deleted {claude_md}")
def _print_project_git_add_hint(paths: list[Path]) -> None:
    unique: list[str] = []
    for path in paths:
        text = path.as_posix().rstrip("/")
        if path.exists() and path.is_dir():
            text += "/"
        if text not in unique:
            unique.append(text)
    if not unique:
        return
    print()
    print("Project-scoped install. Add to version control:")
    print(f"  git add {' '.join(unique)}")
def _claude_pretooluse_hooks(strict: bool = False, project: bool = False) -> "list[dict]":
    """graph_fy's Claude/Codebuddy PreToolUse hooks, resolved at install time.

    The command invokes `graph_fy hook-guard <search|read>` via the absolute exe
    path (`_resolve_graph_fy_exe`) — or, for a project-scoped install, via the
    bare `graph_fy` command, since that config gets committed (#3129). Either
    form parses under sh, cmd.exe and PowerShell alike — this is the #522 fix,
    and mirrors the codex hook. Matchers are
    "Bash|Grep" and "Read|Glob" and the command always contains "graph_fy", so the
    existing install/uninstall filters find and replace both old bash hooks and
    these. "Grep" is in the search matcher because current Claude Code routes
    content search through its dedicated Grep tool, not Bash (#1986) — a
    Bash-only matcher never fired on the agent's primary search path.

    When ``strict`` is set, the read hook carries ``--strict`` so it blocks the
    first raw read per session (Claude Code only). The ``graph_fy_HOOK_STRICT`` env
    var can force it on or off at runtime without a reinstall.

    Each entry carries a ``timeout`` (#3314): unset, Claude Code defaults a
    command hook to 600s, so a single wedged guard (a stuck filesystem, a
    hung subprocess) stalls the surrounding tool call for ten minutes on
    every Bash/Grep/Read/Glob call -- the four highest-frequency tools an
    agent uses. The guard itself measures ~170ms warm; 10s is generous
    headroom over that while still two orders of magnitude below the
    unset default.
    """
    exe = _resolve_graph_fy_exe(project=project)
    if " " in exe and not exe.startswith('"'):
        exe = f'"{exe}"'
    read_cmd = f"{exe} hook-guard read" + (" --strict" if strict else "")
    return [
        {"matcher": "Bash|Grep",
         "hooks": [{"type": "command", "command": f"{exe} hook-guard search", "timeout": 10}]},
        {"matcher": "Read|Glob",
         "hooks": [{"type": "command", "command": read_cmd, "timeout": 10}]},
    ]
def _skill_registration(skill_path: str = "~/.claude/skills/graph_fy/SKILL.md") -> str:
    return (
        "\n# graph_fy\n"
        f"- **graph_fy** (`{skill_path}`) "
        "- code knowledge graph and retrieval layer. Trigger: `/graph_fy`\n"
        "When graph_fy_out/ exists in the project root, refer to it to understand the codebase without fragmentation (code is the source of truth):\n"
        '- Run `graph_fy query "<question>"` for codebase questions before reading raw files.\n'
        "- Check graph_fy_out/GRAPH_REPORT.md and graph_fy_out/wiki/index.md for overall architecture and community structure.\n"
        "When the user types `/graph_fy`, use the installed graph_fy skill or instructions before doing anything else.\n"
    )
def _register_always_on_block(target: Path, prefix: str, registration: str) -> None:
    """Append an always-on registration to *target*, degrading instead of raising.

    The skill files are copied before this runs, so a *target* that cannot be
    read or written must not abort an otherwise-complete install (#3474). That
    happens whenever the dotfile is managed declaratively -- nix/home-manager
    symlinks ``~/.claude/CLAUDE.md`` into a read-only /nix/store, and chezmoi or
    stow with read-only sources leave the same shape.
    """
    try:
        if target.exists():
            content = target.read_text(encoding="utf-8")
            if "graph_fy" in content or "graph_fy" in content:
                print(f"{prefix}already registered (no change)")
            else:
                target.write_text(content.rstrip() + registration, encoding="utf-8")
                print(f"{prefix}skill registered in {target}")
        else:
            _safe_mkdir(target.parent)
            target.write_text(registration.lstrip(), encoding="utf-8")
            print(f"{prefix}created at {target}")
    except OSError as exc:
        print(f"{prefix}skipped: {exc.__class__.__name__}: {exc}", file=sys.stderr)
        print(
            f"  hint: the skill files were installed; add the graph_fy block to "
            f"{target} manually to finish always-on registration",
            file=sys.stderr,
        )
_PLATFORM_CONFIG: dict[str, dict] = {
    "claude": {
        "skill_file": "skill.md",
        "skill_dst": Path(".claude") / "skills" / "graph_fy" / "SKILL.md",
        "claude_md": True,
        "skill_refs": "claude",
    },
    "copilot": {
        "skill_file": "skill-copilot.md",
        "skill_dst": Path(".copilot") / "skills" / "graph_fy" / "SKILL.md",
        "claude_md": False,
        "skill_refs": "copilot",
    },
    "gemini": {
        "skill_file": "skill.md",
        "skill_dst": Path(".gemini") / "config" / "skills" / "graph_fy" / "SKILL.md",
        "claude_md": False,
        "skill_refs": "claude",
    },
    "antigravity": {
        "skill_file": "skill.md",
        "skill_dst": Path(".gemini") / "config" / "skills" / "graph_fy" / "SKILL.md",
        "claude_md": False,
        "skill_refs": "claude",
    },
}
_PLATFORM_ALIASES: dict[str, str] = {
    "agent": "copilot",
    "copilot-agent": "copilot",
    "github-copilot": "copilot",
}
def _canonical_platform(platform_name: str) -> str:
    """Resolve a CLI platform alias to its real _PLATFORM_CONFIG key."""
    return _PLATFORM_ALIASES.get(platform_name.lower(), platform_name)
def _replace_or_append_section(content: str, marker: str, new_section: str) -> str:
    """Idempotently update or append a graph_fy-owned section in shared files.

    If no line is exactly ``marker`` (the heading, at column 0), append
    ``new_section`` to the end (with a blank-line separator if there's existing
    content).

    If a real ``marker`` heading exists, replace the existing section in place.
    The section runs from that heading to the line before the next H2 heading
    (``## `` at line start), or to EOF if no later H2 exists. This lets older
    installs receive the updated copy without users having to uninstall and
    reinstall (issue #580).

    The heading is matched only when a line *is* exactly ``marker`` (after
    stripping surrounding whitespace), never as a substring. Matching ``##
    graph_fy`` inside a bullet or an inline reference used to anchor the replace
    on that mention and delete every line from there to the next heading,
    silently destroying hand-curated content (#1688). When several exact
    headings exist, the last one is used, since graph_fy's section is appended.
    """
    lines = content.split("\n")
    starts = [i for i, line in enumerate(lines) if line.strip() == marker]
    if not starts:
        if content.strip():
            return content.rstrip() + "\n\n" + new_section.lstrip()
        return new_section.lstrip()

    start = starts[-1]
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if lines[j].startswith("## "):
            end = j
            break

    head = "\n".join(lines[:start]).rstrip()
    tail = "\n".join(lines[end:]).lstrip()
    section = new_section.strip()

    parts: list[str] = []
    if head:
        parts.append(head)
    parts.append(section)
    if tail:
        parts.append(tail)
    out = "\n\n".join(parts)
    if not out.endswith("\n"):
        out += "\n"
    return out


def _remove_marker_section(content: str, marker: str, boundary_prefix: str = "## ") -> "str | None":
    """Remove every section whose heading line is exactly ``marker``.

    The heading is matched only when a line *is* exactly ``marker`` (after
    stripping surrounding whitespace), never as a substring. The old uninstall
    regex ``## graph_fy`` was unanchored, so it matched inside a user's
    ``### graph_fy`` heading and deleted hand-written content (#2062) — the same
    class of bug the install side hardened against in #1688. Each section runs to
    the line before the next ``boundary_prefix`` heading (default the next H2) or
    EOF, mirroring ``_replace_or_append_section``. All exact-heading sections are
    removed (pre-#1688 installs could leave duplicates).

    Returns None when no exact ``marker`` line exists — the caller must then leave
    the file untouched. This doubles as the guard: a substring mention (a bullet,
    an inline reference, a deeper ``###`` heading) never triggers a strip.
    """
    lines = content.split("\n")
    removed = False
    while True:
        starts = [i for i, line in enumerate(lines) if line.strip() == marker]
        if not starts:
            break
        start = starts[-1]
        end = len(lines)
        for j in range(start + 1, len(lines)):
            if lines[j].startswith(boundary_prefix):
                end = j
                break
        head = "\n".join(lines[:start]).rstrip()
        tail = "\n".join(lines[end:]).lstrip()
        merged = head + "\n\n" + tail if head and tail else (head or tail)
        lines = merged.split("\n")
        removed = True
    if not removed:
        return None
    return "\n".join(lines).rstrip()


def _print_banner() -> None:
    """Amber brain banner on graph_fy install. TTY-only, never raises."""
    if not sys.stdout.isatty():
        return
    try:
        if sys.platform == "win32":
            import ctypes
            ctypes.windll.kernel32.SetConsoleMode(
                ctypes.windll.kernel32.GetStdHandle(-11), 7
            )
        A = "\033[38;5;214m"
        D = "\033[38;5;130m"
        R = "\033[0m"
        print(f"""{A}
  ╭──◉──╮     ╭──◉──╮
 ╱  ◉   ◉ ╲ ╱ ◉   ◉  ╲
│   ◉─◉─◉  ◉  ◉─◉─◉   │
│    ◉   ◉ │ ◉   ◉    │
│   ◉─◉─◉  ◉  ◉─◉─◉   │
 ╲  ◉   ◉ ╱ ╲ ◉   ◉  ╱
  ╰──◉──╯     ╰──◉──╯
           ◉

  █▀▀ █▀█ ▄▀█ █▀█ █ █     █▀▀ █ █
  █▄█ █▀▄ █▀█ █▀▀ █▀█ ▄▄▄ █▀   █ {D} {__version__}{R}
""")
    except Exception:
        pass
def install(platform: str = "claude", *, project: bool = False, project_dir: Path | None = None) -> None:
    _print_banner()
    platform = _canonical_platform(platform)
    if platform not in _PLATFORM_CONFIG:
        print(
            f"error: unknown platform '{platform}'. Choose from: {', '.join(_PLATFORM_CONFIG)}",
            file=sys.stderr,
        )
        sys.exit(1)

    cfg = _PLATFORM_CONFIG[platform]
    project_dir = project_dir or Path(".")
    skill_dst = _copy_skill_file(platform, project=project, project_dir=project_dir)

    if cfg["claude_md"]:
        # Register in the matching Claude Code scope. Honor CLAUDE_CONFIG_DIR
        # for the global (non-project) case, same as _platform_skill_destination
        # does for the skill copy path (#527) -- this always-on registration
        # path was missed by that fix (#2694).
        if project:
            claude_md = project_dir / ".claude" / "CLAUDE.md"
            skill_ref = ".claude/skills/graph_fy/SKILL.md"
        elif os.environ.get("CLAUDE_CONFIG_DIR"):
            config_dir = Path(os.environ["CLAUDE_CONFIG_DIR"])
            claude_md = config_dir / "CLAUDE.md"
            skill_ref = str(config_dir / "skills" / "graph_fy" / "SKILL.md")
        else:
            claude_md = Path.home() / ".claude" / "CLAUDE.md"
            skill_ref = "~/.claude/skills/graph_fy/SKILL.md"
        _register_always_on_block(
            claude_md, "  CLAUDE.md        ->  ", _skill_registration(skill_ref)
        )

    if project:
        _print_project_git_add_hint([_project_scope_root(skill_dst, project_dir)])

    print()
    print("Done. Open your AI coding assistant and type:")
    print()
    print("  /graph_fy .")
    print()
def _print_install_usage() -> None:
    platforms = ", ".join(_PLATFORM_CONFIG)
    print("Usage: graph_fy install [--project] [--strict] [--platform P|P]")
    print(f"Platforms: {platforms}")
    print("  --strict  block the first raw file read per session until one "
          "`graph_fy query` runs (Claude Code project hook only; needs --project)")
_CLAUDE_MD_MARKER = "## graph_fy"
def _refuse_to_modify(settings_path: Path) -> "NoReturn":
    """Abort a hook install rather than clobber a config file we can't parse (#2167)."""
    print(
        f"[graph_fy] refusing to modify {settings_path}: not valid JSON "
        "(fix or move it and re-run)",
        file=sys.stderr,
    )
    sys.exit(1)
def _read_settings_for_merge(settings_path: Path) -> dict:
    """Load an existing settings/hooks JSON file for a read-modify-write merge.

    A missing file yields a fresh ``{}`` (first install). An existing file that
    cannot be parsed as a JSON object aborts via ``_refuse_to_modify`` instead of
    silently falling back to ``{}`` — the old fallback rewrote the whole file and
    destroyed every setting the user had (#2167). Reads with ``utf-8-sig`` so a
    UTF-8 BOM (the most likely parse-error trigger, same class as #2163) is
    tolerated rather than fatal.
    """
    if not settings_path.exists():
        return {}
    try:
        settings = json.loads(settings_path.read_text(encoding="utf-8-sig"))
    except (json.JSONDecodeError, UnicodeDecodeError, OSError):
        settings = None
    if not isinstance(settings, dict):
        _refuse_to_modify(settings_path)
    return settings
def _write_settings_with_backup(settings_path: Path, settings: dict) -> None:
    """Serialize ``settings`` to ``settings_path``, backing up the previous file.

    Skips the write entirely when the output is identical to what is on disk
    (idempotent re-install: no backup churn, no mtime churn). Otherwise copies
    the existing file to ``<name>.graph_fy-bak`` (single rolling backup) before
    overwriting, so one bad merge can never destroy the user's config (#2167).
    """
    output = json.dumps(settings, indent=2)
    if settings_path.exists():
        if settings_path.read_text(encoding="utf-8") == output:
            return
        backup = settings_path.with_name(settings_path.name + ".graph_fy-bak")
        shutil.copy2(settings_path, backup)
    settings_path.write_text(output, encoding="utf-8")


def _resolve_graph_fy_exe(project: bool = False) -> str:
    """Return the path to the graph_fy executable with forward slashes."""
    import shutil
    if project:
        return "graph_fy"
    found = shutil.which("graph_fy")
    if not found:
        scripts_dir = Path(sys.executable).parent
        for name in ("graph_fy.exe", "graph_fy"):
            candidate = scripts_dir / name
            if candidate.exists():
                found = str(candidate)
                break
    return (found or "graph_fy").replace("\\", "/")


def _project_install(platform_name: str, project_dir: Path | None = None, strict: bool = False) -> None:
    """Install platform skill/config files in the current project."""
    project_dir = project_dir or Path(".")
    platform_name = _canonical_platform(platform_name)
    if platform_name in ("claude", "windows"):
        install(platform=platform_name, project=True, project_dir=project_dir)
        claude_install(project_dir, strict=strict, project=True)
        _print_project_git_add_hint([project_dir / ".claude", project_dir / "CLAUDE.md"])
    elif platform_name == "copilot":
        skill_dst = _copy_skill_file("copilot", project=True, project_dir=project_dir)
        _print_project_git_add_hint([_project_scope_root(skill_dst, project_dir)])
    else:
        install(platform=platform_name, project=True, project_dir=project_dir)


def _project_uninstall(platform_name: str, project_dir: Path | None = None) -> None:
    """Remove project-scoped platform skill/config files only."""
    project_dir = project_dir or Path(".")
    platform_name = _canonical_platform(platform_name)
    if platform_name in ("claude", "windows"):
        _remove_skill_file(platform_name, project=True, project_dir=project_dir)
        _remove_claude_skill_registration(project_dir)
        claude_uninstall(project_dir, project=True)
    elif platform_name == "copilot":
        removed = _remove_skill_file(platform_name, project=True, project_dir=project_dir)
        if not removed:
            print("nothing to remove")
    else:
        _remove_skill_file(platform_name, project=True, project_dir=project_dir)


def _project_uninstall_all(project_dir: Path | None = None) -> None:
    """Remove project-scoped install files without touching user-scope installs."""
    project_dir = project_dir or Path(".")
    print("Uninstalling project-scoped graph_fy files...\n")
    for platform_name in _PLATFORM_CONFIG:
        _project_uninstall(platform_name, project_dir)
def claude_install(project_dir: Path | None = None, strict: bool = False, project: bool = False) -> None:
    """Write the graph_fy section to the local CLAUDE.md."""
    target = (project_dir or Path(".")) / "CLAUDE.md"

    if target.exists():
        content = target.read_text(encoding="utf-8")
        marker = _CLAUDE_MD_MARKER if _CLAUDE_MD_MARKER in content else ("## graph_fy" if "## graph_fy" in content else _CLAUDE_MD_MARKER)
        new_content = _replace_or_append_section(
            content, marker, _always_on("claude-md")
        )
        if new_content == content:
            print(f"graph_fy already configured in {target.resolve()} (no change)")
        else:
            target.write_text(new_content, encoding="utf-8")
            print(f"graph_fy section written to {target.resolve()}")
    else:
        new_content = _always_on("claude-md")
        target.write_text(new_content, encoding="utf-8")
        print(f"graph_fy section written to {target.resolve()}")

    # Always re-install the Claude Code PreToolUse hook so an old hook
    # payload (e.g. pre-issue-#580 wording) is replaced on upgrade.
    _install_claude_hook(project_dir or Path("."), strict=strict, project=project)

    print()
    print("Claude Code will now check the knowledge graph before answering")
    print("codebase questions and rebuild it after code changes.")
    if strict:
        print("Strict mode: the first raw file read per session is blocked until")
        print("one `graph_fy query` runs (toggle with graph_fy_HOOK_STRICT=0).")
def _install_claude_hook(project_dir: Path, strict: bool = False, project: bool = False) -> None:
    """Add graph_fy PreToolUse hook to .claude/settings.json.

    A project-scoped install emits the bare command, since .claude/settings.json
    is then committed and an installing machine's path is wrong there (#3129).
    """
    settings_path = project_dir / ".claude" / "settings.json"
    _safe_mkdir(settings_path.parent)

    settings = _read_settings_for_merge(settings_path)

    hooks = settings.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        _refuse_to_modify(settings_path)
    pre_tool = hooks.setdefault("PreToolUse", [])
    if not isinstance(pre_tool, list):
        _refuse_to_modify(settings_path)

    hooks["PreToolUse"] = [h for h in pre_tool if not (isinstance(h, dict) and h.get("matcher") in ("Glob|Grep", "Bash", "Bash|Grep", "Read|Glob") and ("graph_fy" in str(h) or "graph_fy" in str(h)))]
    hooks["PreToolUse"].extend(_claude_pretooluse_hooks(strict=strict, project=project))
    _write_settings_with_backup(settings_path, settings)
    _mode = " (strict)" if strict else ""
    print(f"  .claude/settings.json  ->  PreToolUse hooks registered (Bash|Grep search + Read/Glob){_mode}")
def _uninstall_claude_hook(project_dir: Path) -> None:
    """Remove the graph_fy PreToolUse hook from .claude/settings.json and its
    local-only sibling .claude/settings.local.json.

    A user may relocate the hook into settings.local.json so it is not committed
    to a shared repo, so uninstall has to clean whichever file holds it (#1731).
    """
    claude_dir = project_dir / ".claude"
    for name in ("settings.json", "settings.local.json"):
        _strip_graph_fy_hook(claude_dir / name)
def _strip_graph_fy_hook(settings_path: Path) -> None:
    """Drop graph_fy PreToolUse hooks from a single Claude settings file, if present."""
    if not settings_path.exists():
        return
    try:
        settings = json.loads(settings_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return
    pre_tool = settings.get("hooks", {}).get("PreToolUse", [])
    filtered = [h for h in pre_tool if not (h.get("matcher") in ("Glob|Grep", "Bash", "Bash|Grep", "Read|Glob") and ("graph_fy" in str(h) or "graph_fy" in str(h)))]
    if len(filtered) == len(pre_tool):
        return
    settings["hooks"]["PreToolUse"] = filtered
    settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
    print(f"  .claude/{settings_path.name}  ->  PreToolUse hook removed")
def _uninstall_binary() -> bool:
    """Attempt to uninstall the tool/package via uv, pipx, or pip."""
    import subprocess

    for tool, prefix in (("uv tool", ["uv", "tool", "uninstall"]), ("pipx", ["pipx", "uninstall"])):
        if shutil.which(prefix[0]):
            for name in ("graph-fy", "graph_fy", "graphify"):
                try:
                    res = subprocess.run([*prefix, name], capture_output=True, text=True)
                    if res.returncode == 0 and ("Uninstalled" in (res.stdout + res.stderr) or tool == "pipx"):
                        print(f"  {tool:<16} ->  uninstalled {name}")
                        return True
                except Exception:
                    pass
    return False



def uninstall_all(project_dir: Path | None = None, purge: bool = False) -> None:
    """Remove graph_fy from every platform detected in the current project."""
    pd = project_dir or Path(".")
    print("Uninstalling graph_fy from all detected platforms...\n")

    # Skill-file / config-section uninstallers. remove_user_skill=True keeps the
    # historical `graph_fy uninstall` behavior: global skill delete plus md/hook
    # cleanup at the project dir (#2215).
    claude_uninstall(pd, remove_user_skill=True)
    _remove_skill_file("copilot")
    _remove_skill_file("gemini")
    _remove_skill_file("antigravity")

    # Git hook
    try:
        from graph_fy.hooks import uninstall as hook_uninstall
        result = hook_uninstall(pd)
        if result:
            print(result)
    except Exception:
        pass

    if purge:
        import shutil as _shutil
        out = pd / _graph_fy_OUT
        if out.exists():
            _shutil.rmtree(out)
            print(f"\n  {_graph_fy_OUT}/  ->  deleted (--purge)")
        else:
            print(f"\n  {_graph_fy_OUT}/  ->  not found (nothing to purge)")

    binary_removed = _uninstall_binary()
    if binary_removed:
        print("\nDone. Skills and binary uninstalled successfully.")
    else:
        print("\nDone. Run 'uv tool uninstall graph_fy' or 'pip uninstall graph_fy' to remove the package itself.")
def claude_uninstall(project_dir: Path | None = None, *, project: bool = False, remove_user_skill: bool | None = None) -> None:
    """Remove the graph_fy skill tree (SKILL.md + references/) and the graph_fy
    section from CLAUDE.md and its local-only variants, plus the PreToolUse hook.

    Mirrors gemini_uninstall: the bare `graph_fy uninstall` and `graph_fy claude
    uninstall` must remove the installed skill, not just strip CLAUDE.md, or the
    progressive-disclosure tree (SKILL.md + references/) is orphaned (#1121).

    A user may relocate the section/hook into the local-only files Claude Code
    supports so they are not committed to a shared repo, so uninstall also cleans
    CLAUDE.local.md, .claude/CLAUDE.local.md and .claude/settings.local.json (#1731).

    Scope rules (#2215): a bare call removes the user-global skill; passing
    ``project_dir`` (or ``project=True``) scopes skill removal to that project
    and leaves the global tree untouched, unless ``remove_user_skill=True``
    explicitly opts back into the global delete (as ``uninstall_all`` does).
    """
    explicit_dir = project_dir is not None
    project_dir = project_dir or Path(".")
    if remove_user_skill is None:
        remove_user_skill = not project and not explicit_dir
    if project or (explicit_dir and not remove_user_skill):
        _remove_skill_file("claude", project=True, project_dir=project_dir)
    if remove_user_skill:
        _remove_skill_file("claude", project=False)

    md_targets = [
        project_dir / "CLAUDE.md",
        project_dir / "CLAUDE.local.md",
        project_dir / ".claude" / "CLAUDE.local.md",
    ]
    existing = [t for t in md_targets if t.exists()]
    removed_any = False
    for target in existing:
        # Not short-circuited: every present file must be cleaned, not just the first.
        if _strip_graph_fy_md_section(target):
            removed_any = True

    if not existing:
        print("No CLAUDE.md found in current directory - nothing to do")
    elif not removed_any:
        print("graph_fy section not found in CLAUDE.md - nothing to do")

    _uninstall_claude_hook(project_dir)
def _strip_graph_fy_md_section(target: Path) -> bool:
    """Strip the ## graph_fy section from one CLAUDE.md-style file.

    Returns True if a section was removed. Deletes the file if nothing else
    remains after removal.
    """
    try:
        content = target.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        # An unreadable/undecodable CLAUDE.md-style file (e.g. non-UTF-8, or a
        # directory of that name) must not abort uninstall - nothing to strip.
        return False
    # Remove graph_fy's ## graph_fy section (heading matched exactly, never as a
    # substring of a user's ### graph_fy) from the marker to the next H2 or EOF.
    cleaned = _remove_marker_section(content, _CLAUDE_MD_MARKER)
    if cleaned is None and "## graph_fy" in content:
        cleaned = _remove_marker_section(content, "## graph_fy")
    if cleaned is None:
        return False
    if cleaned:
        target.write_text(cleaned + "\n", encoding="utf-8")
        print(f"graph_fy section removed from {target.resolve()}")
    else:
        target.unlink()
        print(f"{target.name} was empty after removal - deleted {target.resolve()}")
    return True


_CLI_INSTALL_COMMANDS = frozenset({
    "claude",
    "copilot",
    "agent",
    "gemini",
    "antigravity",
    "install",
    "uninstall",
})


def dispatch_install_cli(cmd: str) -> bool:
    """Handle `graph_fy <install-command>` dispatch (install/uninstall + every
    per-platform install target). Returns True if cmd was an install command and
    was handled, False otherwise so the caller can continue its own dispatch.
    Moved verbatim from __main__.main().
    """
    if cmd not in _CLI_INSTALL_COMMANDS:
        return False
    if cmd == "install":
        default_platform = "claude"
        selected_platform: str | None = None
        project_scope = False
        strict = False
        args = sys.argv[2:]
        i = 0
        while i < len(args):
            arg = args[i]
            if arg in ("-h", "--help"):
                _print_install_usage()
                return True
            if arg == "--project":
                project_scope = True
                i += 1
            elif arg == "--strict":
                strict = True
                i += 1
            elif arg.startswith("--platform="):
                candidate = arg.split("=", 1)[1]
                if selected_platform and selected_platform != candidate:
                    print("error: specify install platform only once", file=sys.stderr)
                    sys.exit(1)
                selected_platform = candidate
                i += 1
            elif arg == "--platform":
                if i + 1 >= len(args):
                    print("error: --platform requires a value", file=sys.stderr)
                    sys.exit(1)
                candidate = args[i + 1]
                if selected_platform and selected_platform != candidate:
                    print("error: specify install platform only once", file=sys.stderr)
                    sys.exit(1)
                selected_platform = candidate
                i += 2
            elif arg.startswith("-"):
                print(f"error: unknown install option '{arg}'", file=sys.stderr)
                sys.exit(1)
            else:
                if selected_platform and selected_platform != arg:
                    print("error: specify install platform only once", file=sys.stderr)
                    sys.exit(1)
                selected_platform = arg
                i += 1
        chosen_platform = _canonical_platform(selected_platform or default_platform)
        if project_scope:
            _project_install(chosen_platform, Path("."), strict=strict)
        else:
            if strict:
                print(
                    "note: --strict applies to the project PreToolUse hook; run "
                    "`graph_fy install --project --strict` or `graph_fy claude install --strict`.",
                    file=sys.stderr,
                )
            install(platform=chosen_platform)
    elif cmd == "uninstall":
        args = sys.argv[2:]
        purge = "--purge" in args
        project_scope = "--project" in args
        selected_platform = None
        i = 0
        while i < len(args):
            arg = args[i]
            if arg in ("--purge", "--project"):
                i += 1
            elif arg.startswith("--platform="):
                selected_platform = arg.split("=", 1)[1]
                i += 1
            elif arg == "--platform":
                if i + 1 >= len(args):
                    print("error: --platform requires a value", file=sys.stderr)
                    sys.exit(1)
                selected_platform = args[i + 1]
                i += 2
            elif arg.startswith("-"):
                print(f"error: unknown uninstall option '{arg}'", file=sys.stderr)
                sys.exit(1)
            else:
                selected_platform = arg
                i += 1
        if project_scope:
            if selected_platform:
                _project_uninstall(_canonical_platform(selected_platform), Path("."))
            else:
                _project_uninstall_all(Path("."))
        else:
            if selected_platform:
                _remove_skill_file(_canonical_platform(selected_platform))
            else:
                uninstall_all(purge=purge)
    elif cmd == "claude":
        subcmd = sys.argv[2] if len(sys.argv) > 2 else ""
        if subcmd == "install":
            _strict = "--strict" in sys.argv[3:]
            if "--project" in sys.argv[3:]:
                _project_install("claude", Path("."), strict=_strict)
            else:
                install(platform="claude")
                claude_install(strict=_strict)
        elif subcmd == "uninstall":
            if "--project" in sys.argv[3:]:
                _project_uninstall("claude", Path("."))
            else:
                claude_uninstall()
        else:
            print("Usage: graph_fy claude [install|uninstall]", file=sys.stderr)
            sys.exit(1)

    elif cmd in ("copilot", "agent", "gemini", "antigravity"):
        target = _canonical_platform(cmd)
        subcmd = sys.argv[2] if len(sys.argv) > 2 else ""
        if subcmd == "install":
            if "--project" in sys.argv[3:]:
                _project_install(target, Path("."))
            else:
                install(platform=target)
        elif subcmd == "uninstall":
            if "--project" in sys.argv[3:]:
                _project_uninstall(target, Path("."))
            else:
                removed = _remove_skill_file(target)
                print("skill removed" if removed else "nothing to remove")
        else:
            print(f"Usage: graph_fy {cmd} [install|uninstall]", file=sys.stderr)
            sys.exit(1)
    else:
        return False
    return True
